version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    environment:
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Grant access to dependencies
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Dependencies
          command: |
            pip install --upgrade pip
            sudo pip install pipenv
            pipenv install
      - run:
          name: Check with Pylint
          command: |
            pipenv run pylint *.py --rcfile=.pylintrc
            pipenv run pylint experiments/example/*.py
            pipenv run pylint experiments/tmhmm3/*.py --rcfile=.pylintrc
            pipenv run pylint pnerf/*.py --rcfile=.pylintrc
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"